// Autogenerated by String Creator
// Made by Tobias K.

namespace Dharma_DSharp.Constants
{
    public static class Strings
    {
        /// <summary>
        /// The description of the command that is displayed when pressing /.
        /// 0 will be replaced with @Arks_Operative
        /// </summary>
        public const string GrantCommandDescription = @"Grants the mentioned homie the arks operative role.";

        /// <summary>
        /// The name of the user parameter (displayed in blue) => all lowercase, else it will crash
        /// </summary>
        public const string GrantCommandUserParameterName = @"homie";

        /// <summary>
        /// The description of the user parameter that is displayed when the grant command is selected
        /// </summary>
        public const string GrantCommandUserParameterDescription = @"Verify that the homie is within the Alliance in-game before granting the role.";

        /// <summary>
        /// The text that is displayed when a user tries to use that grant command that isn't allowed to
        /// </summary>
        public const string GrantCommandNotAllowed = @"ERROR, PERMISSION NOT GRANTED";

        /// <summary>
        /// The response that the bot will send if the grant command was successful
        /// {0} will be replaced with the mentioned user.
        /// </summary>
        public const string GrantCommandResponse = @"{0} has officially joined the crew.";

        /// <summary>
        /// The response that the bot will send if the user already got the arks operative role
        /// {0} will be the mentioned user
        /// </summary>
        public const string GrantCommandAlreadyGrantedResponse = @"{0} is already on board!";

        /// <summary>
        /// Will be displayed if the user that should
        /// be granted didn't accept the rules (doesn't have homie role)
        /// {0} is the user that should be granted but didn't accept the rules
        /// </summary>
        public const string GrantCommandNeedsToAcceptRules = @"{0} needs to accept the rules before being able to be granted.";

        /// <summary>
        /// Title of the welcome embed.
        /// </summary>
        public const string WelcomeTitle = @"Please give a warm welcome to our newest guest~";

        /// <summary>
        /// 0 = UserId, 1 = Dharma GuildId, 2 = StartHere Channel-Id
        /// </summary>
        public const string WelcomeDescription = @"Welcome to Dharma <@{0}>!\n Please head over to[#start-here](https://discord.com/channels/{1}/{2}) to get basic access to several parts of our community.";

        /// <summary>
        /// Color in RGB Hex format
        /// </summary>
        public const string WelcomeEmbedColor = @"#00FF7F";

        /// <summary>
        /// The welcome gif that is sent with the welcome embed.
        /// </summary>
        public const string WelcomeFooterImage = @"https://i.imgur.com/uc89PmB.gif";

        /// <summary>
        /// Needs to be packed with the bot at some point, url is spooky. Is the yin/yang symbol.
        /// </summary>
        public const string WelcomeThumbnailUrl = @"https://i.imgur.com/JQIxLPQ.png";

        /// <summary>
        /// Title of the user got kicked embed.
        /// </summary>
        public const string UserKickedTitle = @"";

        /// <summary>
        /// 0 is replaced with the user id.
        /// </summary>
        public const string UserKickedDescription = @"Welp, we tried <@{0}>.";

        /// <summary>
        /// Color of the kicked embed
        /// </summary>
        public const string UserKickedEmbedColor = @"#FFA500";

        /// <summary>
        /// Not used at the moment. Is implemented tho.
        /// </summary>
        public const string UserKickedFooterImage = @"";

        /// <summary>
        /// Not used at the moment. Is implemented tho.
        /// </summary>
        public const string UserKickedThumbnailUrl = @"";

        /// <summary>
        /// Not used at the moment. Is implemented tho.
        /// </summary>
        public const string UserBannedTitle = @"";

        /// <summary>
        /// 0 is replaced with the member id
        /// </summary>
        public const string UserBannedDescription = @"Goodbye <@{0}>. We tried.";

        /// <summary>
        /// Color of the banned embed
        /// </summary>
        public const string UserBannedEmbedColor = @"#7F0000";

        /// <summary>
        /// Footer image of the ban embed. Value needs to be packed with the bot at some point
        /// </summary>
        public const string UserBannedFooterImage = @"https://c.tenor.com/S-Lbnq4B-KUAAAAM/good-bye-bye-bye.gif";

        /// <summary>
        /// Not used at the moment. Is implemented tho.
        /// </summary>
        public const string UserBannedThumbnailUrl = @"";

        /// <summary>
        /// Not used at the moment. Is implemented tho.
        /// </summary>
        public const string UserLeftTitle = @"";

        /// <summary>
        /// 0 is replaced with the member id
        /// </summary>
        public const string UserLeftDescription = @"Welp, we tried <@{0}>.";

        /// <summary>
        /// Color of the user left embed
        /// </summary>
        public const string UserLeftEmbedColor = @"#99AAB5";

        /// <summary>
        /// Not used at the moment. Is implemented tho.
        /// </summary>
        public const string UserLeftFooterImage = @"";

        /// <summary>
        /// Not used at the moment. Is implemented tho.
        /// </summary>
        public const string UserLeftThumbnailUrl = @"";

        /// <summary>
        /// 
        /// </summary>
        public const string DharmaEmbedFooter = @"The Dharma Team";
    }
}
