// <auto-generated />
using System;
using Dharma_DSharp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dharma_DSharp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220526071327_AddNoteToMember")]
    partial class AddNoteToMember
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("Dharma_DSharp.Models.AllianceMember", b =>
                {
                    b.Property<ulong>("DiscordUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiscordDisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscordUserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastActivityUpdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhantasyUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DiscordUserId");

                    b.ToTable("Member");
                });
#pragma warning restore 612, 618
        }
    }
}
